# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6717ed8bb764d36fc99310b42ed9f4facaaa31d347e072e25bdf3cb21b04dc66d933bcf35e5c11d52bce137e4da299dc5029623f9f70c51f343e70a83a91da59

test:
  secret_key_base: 28ddbacd6aefe6c07ca5b340d13e89c53975bcbbd0b0dd88f7659d0dc9f8708c86b87d67ea05fd46e44b54a035cccab48606f0ac5a3ad893afa3557c096e6e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
